homeTask7
MaksimKuznets/myNewRepository pull request #10
Opened 2022-03-13 21:36 UTC by MaksimKuznets

2022-03-15 16:25 UTC, EgorAntonovich requested changes

2022-03-15 16:25 UTC, EgorAntonovich commented on homeTask_7/homeTask_7/Person.cs
> +        public Person()
Do we need this?

2022-03-15 16:25 UTC, EgorAntonovich commented on homeTask_7/homeTask_7/Employee.cs
> +        public abstract string GetAction();
Why you aren't use this?

2022-03-15 16:45 UTC, MaksimKuznets commented on homeTask_7/homeTask_7/Person.cs
> +        public Person()
> Do we need this?
Do you mean the узьен constructor?

2022-03-15 17:03 UTC, MaksimKuznets commented on homeTask_7/homeTask_7/Employee.cs
> +        public abstract string GetAction();
> Why you aren't use this?

So, if you are about GetAction() method, then I really don't use it. I don't remember why i implemented it. I will remove that.

2022-03-15 17:05 UTC, MaksimKuznets commented on homeTask_7/homeTask_7/Person.cs
> +        public Person()
@EgorAntonovich  I will remove implementation of empty constructor

2022-03-22 12:33 UTC, EgorAntonovich approved these changes
Looks good

2022-03-22 21:33 UTC, merged